import React from 'react'
import Footerr from './Footer'
import NavigationBar from './NavigationBar'

export default function Pvc() {
  return (
    <div>
<NavigationBar/>

<div className='container mx-auto mt-5 p-4'> 
<span className='fs-1 text-secondary'> Privacy Policy</span><br /><br />

Updated on 2021-05-01 <br /><br />
MediTech Labs (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your 
personal information is collected, used, and disclosed by MediTech Labs.
This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our 
application, MediTech Labs. By accessing or using our Service, you signify that you have read, understood, and agree 
to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and 
our Terms of Service. <br /> <br />
Definitions and key terms <br /><br />
To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are 
strictly defined as:
 Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify 
your browser, provide analytics, remember information about you such as your language preference.
 Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to MediTech Labs, that is responsible for your information under this Privacy Policy.
 Country: where MediTech Labs or the owners/founders of MediTech Labs are based, in this case is Sri Lanka
 Customer: refers to the company, organization or persons that use the MediTech Labs Services.
 Device: any internet connected device such as a phone, tablet, computer or any other device that can be 
used to visit MediTech Labs and use the services.
 IP address: Every device connected to the Internet is assigned a number known as an Internet protocol 
(IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to 
identify the location from which a device is connecting to the Internet.
 Personnel: refers to those individuals who are employed by MediTech Labs or are under contract to perform 
a service on behalf of one of the parties.
 Personal Data: any information that directly, indirectly, or in connection with other information —
including a personal identification number — allows for the identification or identifiability of a natural 
person.
 Service: refers to the service provided by MediTech Labs.
 Website: MediTech Labs."’s" site, which can be accessed via this URL: www.MediTech Labshealth.com
 You: a person or entity that uses MediTech Labs Services.
<br /><br />
What Information Do We Collect?<br /><br />
We collect information from you when you require to contact us or to use our online payment portals.
 -Name 
 -Age 
 -Gender 
 -Phone Numbers
 -Email Addresses
 -Any other payment related information. 
 <br /><br />
How Do We Use the Information We Collect?<br /><br />
Any of the information we collect from you may be used in one of the following ways:
 -To personalize your experience (your information helps us to better respond to your individual needs)
 -To improve our website (we continually strive to improve our website offerings based on the information and 
feedback we receive from you)
 -To improve customer service (your information helps us to more effectively respond to your customer service 
requests and support needs)
 -To process payment transactions<br /><br />
Where and when is information collected from customers and end users?<br /><br />
MediTech Labs will collect personal information that you submit to us. <br /><br />
How Do We Use Your Email Address?<br /><br />
By submitting your email address on this website, you agree to receive emails from us. We use your email address 
to send our feedbacks and payment related information.<br /><br />
How Long Do We Keep Your Information?<br /><br />
We keep your information only so long as we need it to provide MediTech Labs to you and fulfill the purposes described 
in this policy. <br /><br />
How Do We Protect Your Information?<br /><br />
We implement a variety of security measures to maintain the safety of your personal information when you place 
an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied 
sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our 
Payment gateway providers database only to be accessible by those authorized with special access rights to such 
systems, and are required to keep the information confidential. After a transaction, your private information (credit 
cards, financials, etc.) is never kept with us. Such information is directly handled by payment gateways.
Is the information collected through the MediTech Labs Service secure?
We take precautions to protect the security of your information. We have physical, electronic, and managerial 
procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your 
information. However, neither people nor security systems are foolproof, including encryption systems. In 
addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use 
reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable 
law imposes any non-disclaimable duty to protect your personal information, you agree that intentional 
misconduct will be the standards used to measure our compliance with that duty.<br /><br />
Governing Law<br /><br />
This Privacy Policy is governed by the laws of Sri Lanka without regard to its conflict of laws provision. You consent 
to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under 
or in connection with this Privacy Policy, except for those individuals who may have rights to make claims under 
Privacy Shield, or the Swiss-US framework.
The laws of Sri Lanka, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. 
Your use of the website may also be subject to other local, state, national, or international laws.
By using MediTech Labs or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree 
to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, 
direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect 
the use or disclosure of your personal information will mean that you accept those changes.<br /><br />
Your Consent<br /><br />
We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit 
our site and how it's being used. By using our website, registering an account, or making a payment, you hereby 
consent to our Privacy Policy and agree to its terms.
<br /><br />

Payment Details<br /><br />
In respect to any payment processing details you have provided us, we commit that this confidential information 
will be stored in the most secure manner possible.
Changes to Our Privacy Policy
We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they 
accurately reflect our Service and policies. When you continue to use the Service, you will be bound by the updated 
Privacy Policy. 

</div>
<Footerr/>
    </div>
  )
}
